name: invictus
description: "The invictus SDK for Flutter."
version: 1.0.0-dev.0
repository: https://github.com/yanshouwang/invictus
issue_tracker: https://github.com/yanshouwang/invictus/issues

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  invictus_api: ^1.0.0-dev.0
  invictus_android: ^1.0.0-dev.0
  invictus_darwin: ^1.0.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: invictus_android
      ios:
        default_package: invictus_darwin
      macos:
        default_package: invictus_darwin
