name: invictus
description: "The invictus SDK for Flutter."
version: 0.0.1
repository: https://github.com/yanshouwang/invictus
issue_tracker: https://github.com/yanshouwang/invictus/issues

resolution: workspace

environment:
  sdk: ^3.9.2
  flutter: ">=3.3.0"

dependencies:
  flutter:
    sdk: flutter
  invictus_api: ^0.0.1
  invictus_android: ^0.0.1
  invictus_darwin: ^0.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        default_package: invictus_android
      ios:
        default_package: invictus_darwin
      macos:
        default_package: invictus_darwin
