name: invictus_darwin
description: "iOS and macOS implementation of the invictus plugin."
version: 1.0.0-dev.0
repository: https://github.com/yanshouwang/invictus
issue_tracker: https://github.com/yanshouwang/invictus/issues

resolution: workspace

environment:
  sdk: ^3.9.2
  # Flutter versions prior to 3.7 did not support the
  # sharedDarwinSource option.
  flutter: ">=3.7.0"

dependencies:
  flutter:
    sdk: flutter
  invictus_api: ^1.0.0-dev.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    implements: invictus
    platforms:
      ios:
        sharedDarwinSource: true
        pluginClass: InvictusDarwinPlugin
        dartPluginClass: InvictusDarwinPlugin
      macos:
        sharedDarwinSource: true
        pluginClass: InvictusDarwinPlugin
        dartPluginClass: InvictusDarwinPlugin
